trigger:
  - master
jobs:
  - job: CreateDocs
    variables:
      skipComponentGovernanceDetection: true
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: |
          Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.43.2/docfx.zip" `
          -OutFile "docfx.zip" | Wait-Process; Expand-Archive -Path "docfx.zip" -DestinationPath "./docfx/"
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Download and Extract DocFX
      - task: CmdLine@2
        displayName: Provision DocFX Directory
        inputs:
          script: $(Build.BinariesDirectory)/docfx/docfx.exe init -q
          workingDirectory: $(Build.SourcesDirectory)
          failOnStderr: true
      - powershell: ls
        workingDirectory: $(Build.SourcesDirectory)/docfx_project/
      - powershell: |
          Copy-Item "$(Build.SourcesDirectory)/eng/docgeneration/docfx.json" -Destination "$(Build.SourcesDirectory)/docfx_project/" -Force
        displayName: Copy over docfx.json
      - task: CmdLine@2
        displayName: Generate MetaData
        inputs:
          script: $(Build.BinariesDirectory)/docfx/docfx.exe metadata
          workingDirectory: $(Build.SourcesDirectory)/docfx_project/
          failOnStderr: true
      - task: PowerShell@2
        displayName: 'Structure DocFx Site'
        inputs:
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/eng/docgeneration/script/Structure-DocfxSite.ps1'
          arguments: '-SourceDirectory $(Build.SourcesDirectory)'
          failOnStderr: true
      - task: CmdLine@2
        displayName: Build Doc Content
        inputs:
          script: $(Build.BinariesDirectory)/docfx/docfx.exe build
          workingDirectory: $(Build.SourcesDirectory)/docfx_project/
          failOnStderr: true
      - powershell: |
          Copy-Item "$(Build.SourcesDirectory)/eng/docgeneration/assets/*" -Destination "$(Build.SourcesDirectory)/docfx_project/_site/" -Force
        displayName: Replace site assets
      - task: CopyFiles@2
        displayName: Copy HTML to Artifacts Directory
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/docfx_project/
          content: '**\*'
          targetFolder: $(Build.ArtifactStagingDirectory)/docfx_project
          overWrite: true
      - task: PublishPipelineArtifact@0
        condition: succeeded()
        inputs:
          artifactName: docfx_project
          targetPath: $(Build.ArtifactStagingDirectory)/docfx_project/_site