trigger:
  - master
jobs:
  - job: CreateDocs
    variables:
      skipComponentGovernanceDetection: true
    pool:
      vmImage: vs2017-win2016
    steps:
      # These steps copy dlls from the build ci pipeline and structure them for doc generation
      - powershell: |
          New-Item -Type dir dll-docs/my-api
        workingDirectory: $(Build.BinariesDirectory)
      - task: DownloadPipelineArtifact@2
        displayName: 'Download published packages'
        inputs:
          buildType: specific
          project: '590cfd2a-581c-4dcb-a12e-6568ce786175'
          definition: 37
          buildVersionToDownload: latestFromBranch
          tags: Scheduled
          artifactName: packages
          targetPath: '$(System.ArtifactsDirectory)/packages'
      - powershell: ls
        workingDirectory: $(System.ArtifactsDirectory)
      - powershell: ls
        workingDirectory: $(System.ArtifactsDirectory)/packages
      - task: PowerShell@2
        displayName: Extract dlls from packages and copy then to dlls directory
        inputs:
          targetType: filePath
          filePath: $(Build.SourcesDirectory)/eng/docgeneration/script/extractdlls.ps1
          arguments: '-PkgDirPath $(System.ArtifactsDirectory)/packages -DllDirPath $(Build.BinariesDirectory)/dll-docs/my-api'
          failOnStderr: true
      - powershell: ls
        workingDirectory: $(Build.BinariesDirectory)/dll-docs/my-api
      - task: NuGetToolInstaller@0
        displayName: Install Nuget Client
      - powershell: nuget install NETStandard.Library -ExcludeVersion
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Install NETStandard.Library
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.BinariesDirectory)/dll-docs/dependencies/my-api'
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)/NETStandard.Library/build/netstandard2.0/ref'
          TargetFolder: '$(Build.BinariesDirectory)/dll-docs/dependencies/my-api'
      - powershell: ls
        workingDirectory: $(Build.BinariesDirectory)/dll-docs/dependencies
      - powershell: ls
        workingDirectory: $(Build.BinariesDirectory)/dll-docs/dependencies/my-api
      
