name: Follow up on DevOps run test

on:
  check_suite:
    types: [completed]
  issue_comment:
    types: [created]

permissions: {}

jobs:
  event-handler:
    permissions:
      statuses: write # to set status (azure/azure-sdk-actions)
      pull-requests: write # to read pull requests and write comments (azure/azure-sdk-actions)
      checks: read # to read check status (azure/azure-sdk-actions)
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    runs-on: ubuntu-latest # This image is intentionally set to "latest", and not to a specific version
    steps:
      - name: Dump check_suite payload
        run: |
          Write-Host "Event: ${{ github.event_name }}"
          Write-Host "Check suite ID: ${{ github.event.check_suite.id }}"
          Write-Host "Check suite status: ${{ github.event.check_suite.status }}"
          Write-Host "Check suite conclusion: ${{ github.event.check_suite.conclusion }}"
          Write-Host "Commit SHA: ${{ github.event.check_suite.head_sha }}"
          Write-Host "Repository name: ${{ github.event.repository.name }}"
        shell: pwsh