name: Follow up on DevOps run test

on:
  check_suite:
    types: [completed]
  issue_comment:
    types: [created]

permissions: {}

jobs:
  event-handler:
    permissions:
      statuses: write # to set status (azure/azure-sdk-actions)
      pull-requests: write # to read pull requests and write comments (azure/azure-sdk-actions)
      checks: read # to read check status (azure/azure-sdk-actions)
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    runs-on: ubuntu-latest # This image is intentionally set to "latest", and not to a specific version
    steps:
      - name: Get Pull Request Information
        run: |
          $check_suite = '${{ toJson(github.event.check_suite) }}'
          Write-Host $check_suite
          $prs = '${{ toJson(github.event.check_suite.pull_requests) }}'
          Write-Host $prs
          $prsAsArray = $prs | ConvertFrom-Json
          
          foreach ($pr in $prsAsArray) {
            Write-Host "headSHA: $($pr.head.sha)"
            Write-Host "repoName: $($pr.base.repo.name)"
            Write-Host "url: $($pr.url)"
            Write-Host "number: $($pr.number)"
          }
        shell: pwsh