name: Follow up on DevOps run test

on:
  check_suite:
    types: [completed]
  issue_comment:
    types: [created]

permissions: {}

jobs:
  event-handler:
    permissions:
      statuses: write # to set status (azure/azure-sdk-actions)
      pull-requests: write # to read pull requests and write comments (azure/azure-sdk-actions)
      checks: read # to read check status (azure/azure-sdk-actions)
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    runs-on: ubuntu-latest # This image is intentionally set to "latest", and not to a specific version
    steps:
      - name: Get Pull Request Information
        run: Write-Host '${{ toJson(github.event.check_suite) }}'
        shell: pwsh