name: Follow up on DevOps run test

on:
  check_suite:
    types: [completed]
  issue_comment:
    types: [created]

permissions: {}

jobs:
  event-handler:
    permissions:
      statuses: write # to set status (azure/azure-sdk-actions)
      pull-requests: write # to read pull requests and write comments (azure/azure-sdk-actions)
      checks: read # to read check status (azure/azure-sdk-actions)
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    runs-on: ubuntu-latest # This image is intentionally set to "latest", and not to a specific version
    steps:
      - name: Get Pull Request Information
        if: ${{ github.event.check_suite.pull_requests && github.event.check_suite.pull_requests | length > 0 }}
        run: |
          $prs = ${{ toJson(github.event.check_suite.pull_requests) }}
          foreach ($pr in $prs) {
            echo "url: $pr.url"
            echo "number: $pr.number"
            echo "headSHA: $pr.head.sha"
            echo "repoName: $pr.repo.name"
          }
        shell: pwsh